<?php
/*======================================================================*\
|| #################################################################### ||
|| # Package - Joomla Template based on YJSimpleGrid Framework          ||
|| # Copyright (C) 2010  Youjoomla.com. All Rights Reserved.            ||
|| # license - PHP files are licensed under  GNU/GPL V2                 ||
|| # license - CSS  - JS - IMAGE files  are Copyrighted material        ||
|| # bound by Proprietary License of Youjoomla.com                      ||
|| # for more information visit http://www.youjoomla.com/license.html   ||
|| # Redistribution and  modification of this software                  ||
|| # is bounded by its licenses                                         ||
|| # websites - http://www.youjoomla.com | http://www.yjsimplegrid.com  ||
|| #################################################################### ||
\*======================================================================*/
defined( '_JEXEC' ) or die( 'Restricted index access' );
/*  
  !!! DO NOT EDIT THIS FILE. IT MIGHT BE CHANGED ON UPDATE
  this file is custom for this template only. if you wish to edit or add 
  own code to the template, use template_name/custom/yjsg_custom_params.php
  
*/
/*

	this variable is for custom link color. you can use it to style any HTML elements
	see instructions here:
	http://www.yjsimplegrid.com/documentation/advanced/elements-styling-based-on-link-color.html

*/
	
$cc_css ="a,.yjsg_features h1,.yjsg_features h4,.yjsgdoclist h1,.yjsgdoclist h4{color:".$style_color.";}";
$cc_css .=".introblock .homelarge {color:".$style_color.";}";

// example of custom layout for specific style. Specific grids get outside divs when blue style is active.
	$yjsg2_before 	= '';
	$yjsg2_after  	= '';
	$yjsg3_before 	= '';
	$yjsg3_after  	= '';
	$yjsg4_before 	= '';
	$yjsg4_after  	= '';
	$yjsg7_before 	= '';
	$yjsg7_after  	= '';
	$footer_before 	= '';
	$footer_after  	= '';
if($css_file == 'blue'){
	$yjsg2_before 	= '<div class="blue_yjsg2_out">';
	$yjsg2_after  	= '</div>';
	$yjsg3_before 	= '<div class="blue_yjsg3_out">';
	$yjsg3_after  	= '</div>';
	$yjsg4_before 	= '<div class="blue_yjsg4_out">';
	$yjsg4_after  	= '</div>';
	$yjsg7_before 	= '<div class="footer_holders">';
	$yjsg7_after  	= '</div>';
	$footer_before 	= '<div class="footer_holders footer">';
	$footer_after  	= '</div>';
}
?>